# Select one of the hardware

all:
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/osal all
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/dal all

clean:	
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/osal clean
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/dal clean
