# Select one of the hardware

all:
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/OSAL all
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/DAL all

clean:	
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/OSAL clean
	make -C $(BOAT_BASE_DIR)/BoAT-SupportLayer/tests/DAL clean
