# Source and Objects


all:
	make -C http2intf all
	make -C rpc all
	make -C storage all
	make -C utilities all


	
clean:
	make -C http2intf clean
	make -C rpc clean
	make -C storage clean
	make -C utilities clean
